name: Build binaries

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # setup python
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Build binaries
              run: |
                  pip install -r requirements.txt
                  pip install pyinstaller
                  pyinstaller --onefile __main__.py